<a href="https://colab.research.google.com/github/Kanka-goswami/IISc_CDS_2302064/blob/main/PNB_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practice Notebook

### Introduction to Numpy
NumPy (Numerical Python) is a python library for scientific computing, that provides high-performance vectors, matrices and higher-dimensional data structures for Python.

## Numpy

####  Exercise 1: Import the numpy package as np.

Hint: use 'import … as …'

In [1]:
import numpy as np

####  Exercise 2: Print the numpy version and the configuration.

Hint: np.__version__, np.show_config

In [3]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

#### Exercise 3: Create an array of 10 zeros and 20 ones.

Hint: np.zeros, np.ones

In [6]:
arr_zero = np.zeros(10,dtype= int)
arr_ones = np.ones(20, dtype= int)
print('array of ten zeros :', arr_zero)
print('array of twenty ones: ', arr_ones)

array of ten zeros : [0 0 0 0 0 0 0 0 0 0]
array of twenty ones:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


####  Exercise 4: Create a vector with values ranging from 10 to 49.

Hint: np.arange

In [8]:
v = np.arange(10,50, dtype= int)
print('Vector ranging from 10 to 49:', v)

Vector ranging from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


####  Exercise 5: Reverse a vector (first element becomes last).

Hint: np.array[::-1]

In [10]:
v_reverse = v[::-1]
print('Vector v reversed:', v_reverse)

Vector v reversed: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


####  Exercise 6: Find the indices of the non-zero elements from [1, 2, 0, 0,  4, 0].

Hint: np.nonzero

In [12]:
ls = [1,2,0,0,4,0]
v1 = np.array(ls)
print('Indices of nonzero elements in vector v1',v1.nonzero())

Indices of nonzero elements in vector v1 (array([0, 1, 4]),)


####  Exercise 7: Create a 3x3 identity matrix.

Hint: np.eye

In [16]:
_3x3_identity_matrix = np.eye(3,3)
print(_3x3_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Exercise 7: Generate a random number between 0 and 1 using numpy.

Hint: np.random.rand()

In [21]:
print(round(np.random.rand(),4))

0.7129


####  Exercise 8: Create a 10x10 array with random values, find the minimum and the maximum values.

Hint: min, max

In [40]:
M = np.random.rand(10,10)
print(M.round(4))
print(f'Maximum value in M:{round(M.max(),4)} and Minimum in M: {round(M.min(),4)}',4)

[[0.3623 0.8481 0.7964 0.4347 0.2627 0.911  0.9433 0.0995 0.598  0.8344]
 [0.5283 0.7326 0.1887 0.4827 0.1447 0.1905 0.2559 0.6411 0.7037 0.9198]
 [0.6192 0.6878 0.0323 0.667  0.3721 0.2618 0.8731 0.4464 0.4346 0.0226]
 [0.3709 0.7667 0.8496 0.0389 0.2068 0.6253 0.2517 0.2522 0.908  0.7137]
 [0.969  0.1708 0.0638 0.5155 0.755  0.4507 0.3109 0.5978 0.239  0.0121]
 [0.4934 0.7386 0.502  0.5694 0.694  0.23   0.4766 0.2214 0.1618 0.045 ]
 [0.2953 0.0605 0.6699 0.8687 0.8102 0.2927 0.2275 0.5643 0.538  0.5332]
 [0.9245 0.5426 0.6293 0.5221 0.9534 0.2482 0.8731 0.483  0.2096 0.2351]
 [0.6167 0.2334 0.3638 0.2595 0.3321 0.1346 0.3089 0.8922 0.1632 0.397 ]
 [0.1416 0.705  0.2186 0.3612 0.7366 0.0208 0.46   0.1027 0.9958 0.3355]]
Maximum value in M:0.9958 and Minimum in M: 0.0121 4


####  Exercise 9: Create a numpy array from the given `List`.

Hint: np.array

In [28]:
ls1 = [2,5,3,7,3,0,0,1]
print(np.array(ls1))

[2 5 3 7 3 0 0 1]


####  Exercise 10: Matrix multiplication for 1-D array.

To multiply the matrix a and b.

Hint: np.dot

In [29]:
a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])

print('scalar product:',np.dot(a,b))

scalar product: 146


####  Exercise 11: Transpose the given array [ [ 1, 2, 3], [ 4, 5, 6],  [ 7, 8, 9], [10, 11, 12] ].
Hint: np.transpose( )

In [35]:
M1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('M1\n',M1)
print('Transposed M:\n', M1.transpose())

M1
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transposed M:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


####  Exercise 12: Given an array *A*, calculate the square root of the elements in it.

Hint: np.sqrt( )

In [39]:
A = np.arange(1,20)

print('square root elementwise of A: \n', np.sqrt(A).round(4))

square root elementwise of A: 
 [1.     1.4142 1.7321 2.     2.2361 2.4495 2.6458 2.8284 3.     3.1623
 3.3166 3.4641 3.6056 3.7417 3.873  4.     4.1231 4.2426 4.3589]


#### Exercise 13: Concatenate two numpy arrays columnwise  by specifying axis = 1.
Hint: np.concatenate( )

In [50]:
c =np.array([[1,2],[3,4]])
d =np.array([[5,6],[7,8]])
print('(c,d) concatenated on axis=0:\n',np.concatenate((c,d),axis=0))
print('(c,d) concatenated on axis=1:\n',np.concatenate((c,d),axis=1))

(c,d) concatenated on axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(c,d) concatenated on axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


#### Exercise 14: Print the second and the third column for the given multidimensional array.


In [52]:
a = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])
print(a[:,1:3])

[[ 4  6]
 [ 6  9]
 [ 8 12]]


####  Exercise 15: For the given multidimensional array:
1. Calculate the mean row wise by specifying axis = 0 and column wise by specifying axis =1.
2. What is the average value of an array?

In [60]:
# 2D array
array = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])
print('row wise mean of array witn axis=0:\n',np.mean(array,axis=0, dtype= int))
print('row wise mean of array witn axis=1:\n',np.mean(array,axis=1, dtype=int))

row wise mean of array witn axis=0:
 [ 3  6  9 12 15]
row wise mean of array witn axis=1:
 [ 6  9 12]


In [62]:
# calculating the average value
array.mean()

9.0

#### Exercise 16: Create an array of all the even numbers from 30 to 70.

In [64]:
even_array = np.arange(30,71,2)
print(even_array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Exercise 17: For the given array, get the slice of the first row and print them.

In [68]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

print(a3[0][:][:])

[[10 11 12]
 [13 14 15]
 [16 17 18]]
